# --- Local QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 50

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "local_qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

# depth k of each submixer
depth_k: 1

# Local Parameters
# by default the starting l should be 0 and should not change
local_observer: True
l_params:
  start_depth_l: 0
  growth_jump: 2
  growth_type: "constant"   # can be either linear, exponent or constant
  update_type: "hard"     # can be either hard or soft
  update_interval_t: 100000

# Reward decomposition variables
decompose_reward: False
reward_parameter_sharing: True
reward_batch_size: 50
reward_updates_per_batch: 1
reward_diff_threshold: 0.5
reward_acc: 0.90

# parameter sharing for the subnet (only relevant for symmetric problems)
parameter_sharing: True

name: "local_qmix"
