env: payoff_matrix

env_args:
  a: 30.0
  episode_limit: 2.0

display_q_values: True
test_greedy: True
test_nepisode: 10
test_interval: 1000
log_interval: 1000
save_vid_interval: 10000000000
runner_log_interval: 500
learner_log_interval: 500
t_max: 50000
